name: flutter_mvvm_getx
description: A new flutter project , mvvm pattern & getx state managment .
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.5.1
  get_storage:
#  json_annotation: ^4.4.0
  freezed_annotation: ^1.1.0
  freezed: ^1.1.1
  shimmer:
  delayed_display: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner:
  json_serializable: ^6.1.5
  mockito: ^5.1.0
flutter:
  uses-material-design: true

  assets:
    - assets/userProfile.json

  fonts:
    - family: IRANSans_Medium
      fonts:
        - asset: assets/fonts/IRANSansMedium.ttf